# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rv__j2ghsE6PwlTaXBEkfp6WhY0q1tj8
"""

import os
print(os.listdir("/content"))

import pandas as pd  # Import pandas library for data processing

df = pd.read_csv("/content/creditcard_clean.csv")

# Check basic information of the dataset
print(df.info())

# Statistical description of each column
print(df.describe())

# Check for missing values in each column
print(df.isnull().sum())

import seaborn as sns  # Import seaborn for visualization
import matplotlib.pyplot as plt  # Import matplotlib for displaying plots

!pip install seaborn

# View all column names of the dataset
print(df.columns)

# Check the distribution of target variable 'Class'
sns.countplot(x='Class', data=df)  # 'Class' is the target variable (0=Non-Fraud, 1=Fraud)
plt.title("Fraud Distribution")
plt.show()

# Distribution of numerical features
import matplotlib.pyplot as plt

# Distribution of numerical features
df.select_dtypes(include=['float64', 'int64']).hist(bins=20, figsize=(15, 15))  # Increase figure size
plt.tight_layout()  # Automatically adjust spacing between subplots
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Calculate correlation matrix
corr = df.corr()

# Plot correlation heatmap
plt.figure(figsize=(18, 16))  # Increase figure size
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5, vmax=1, vmin=-1)
plt.title("Correlation Heatmap of All Features")
plt.tight_layout()
plt.show()

# Filter highly correlated features: set threshold (e.g., 0.8)
threshold = 0.8
high_corr = corr[(corr > threshold) & (corr != 1)]

# Output pairs of highly correlated features
high_corr_pairs = high_corr.stack().reset_index()
high_corr_pairs.columns = ['Feature 1', 'Feature 2', 'Correlation']
high_corr_pairs = high_corr_pairs[high_corr_pairs['Feature 1'] != high_corr_pairs['Feature 2']]  # Exclude self-correlation

# View pairs of highly correlated features
print(high_corr_pairs)

import matplotlib.pyplot as plt

# Calculate the number of positive and negative samples
class_counts = df['Class'].value_counts()

# Plot pie chart
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('creditcard_clean.csv')

df.columns = df.columns.str.strip()

…    labels=['Non-Fraud (0)', 'Fraud (1)'],
    autopct='%1.2f%%',
    startangle=90,
    colors=['lightblue', 'lightcoral']
)

plt.title("Distribution of Fraud and Non-Fraud Transactions")
plt.axis('equal')  
plt.show()

# Check the relationship between numerical features and target variable
sns.boxplot(x='Class', y='Amount', data=df)  # 'Class' is target variable, 'Amount' is transaction amount feature
plt.title("Fraud vs Amount")
plt.show()

# Scatter plot: Relationship between transaction time and amount
sns.scatterplot(x='Time', y='Amount', hue='Class', data=df)  # 'Time' and 'Amount' are column names, 'Class' is target variable
plt.title("Time vs Amount (Fraud vs Non-fraud)")
plt.show()

# Use box plot to detect outliers in Amount feature
sns.boxplot(x='Amount', data=df)  # 'Amount' is the column name for transaction amount
plt.title("Amount Distribution (Outliers)")
plt.show()
